sudo: required
services:
  - docker
before_install: 
  - docker build -t anilkumar/docker-react -f Dockerfile.dev .
script: 
  - docker run anilkumar/docker-react npm run test -- --coverage
deploy:
   provider: elasticbeanstalk
   region: us-east-2
   app: docker
   env: docker-env
   bucket_name: docker-test-elb
   bucket_folder: docker
   on: 
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: "$AWS_SECRET_KEY"

   

